services:
  - type: web
    name: neonflix-huzaifa23
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node proxy_backend.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        sync: false  
      - key: ADMIN_PASSWORD
        sync: false   
      - key: ALLOWED_ORIGIN
        value: https://neonflix-huzaifa23.onrender.com  